import isas, { autoInstall, install } from './plugin.js';
import { Isas } from './isas.js';
import { Alert } from './components/alert/alert.js';
import { Avatar } from './components/avatar/avatar.js';
import { Badge } from './components/badge/badge.js';
import { Button } from './components/button/button.js';
import { Card } from './components/card/card.js';
import { Chat } from './components/chat/chat.js';
import { Countdown } from './components/countdown/countdown.js';
import { Dialog } from './components/dialog/dialog.js';
import { DialogTrigger } from './components/dialog/dialog-trigger.js';
import { Divider } from './components/divider/divider.js';
import { Dock } from './components/dock/dock.js';
import { Dropdown } from './components/dropdown/dropdown.js';
import { DropdownTrigger } from './components/dropdown/dropdown-trigger.js';
import { Input } from './components/input/input.js';
import { InputField } from './components/input-field/input-field.js';
import { List } from './components/list/list.js';
import { Menu } from './components/menu/menu.js';
import { Option } from './components/option/option.js';
import { Otp } from './components/otp/otp.js';
import { Overlay } from './components/overlay/overlay.js';
import { OverlayTrigger } from './components/overlay/overlay-trigger.js';
import { Progress } from './components/progress/progress.js';
import { RadialProgress } from './components/radial-progress/radial-progress.js';
import { Select } from './components/select/select.js';
import { SelectControl } from './components/select/select-control.js';
import { SelectField } from './components/select-field/select-field.js';
import { Steps } from './components/steps/steps.js';
import { Stats } from './components/stats/stats.js';
import { TabContent } from './components/tabs/tab-content.js';
import { TabPanels } from './components/tabs/tab-panels.js';
import { Tabs } from './components/tabs/tabs.js';
import { Timeline } from './components/timeline/timeline.js';
import { Tooltip } from './components/tooltip/tooltip.js';

Isas.components.register('alert', Alert);
Isas.components.register('button', Button);
Isas.components.register('badge', Badge);
Isas.components.register('countdown', Countdown);
Isas.components.register('dialog', Dialog);
Isas.components.register('dialog-trigger', DialogTrigger);
Isas.components.register('avatar', Avatar);
Isas.components.register('menu', Menu);
Isas.components.register('option', Option);
Isas.components.register('select', Select);
Isas.components.register('select-control', SelectControl);
Isas.components.register('select-field', SelectField);
Isas.components.register('divider', Divider);
Isas.components.register('dock', Dock);
Isas.components.register('dropdown', Dropdown);
Isas.components.register('dropdown-trigger', DropdownTrigger);
Isas.components.register('card', Card);
Isas.components.register('chat', Chat);
Isas.components.register('input', Input);
Isas.components.register('input-field', InputField);
Isas.components.register('list', List);
Isas.components.register('otp', Otp);
Isas.components.register('tooltip', Tooltip);
Isas.components.register('overlay', Overlay);
Isas.components.register('overlay-trigger', OverlayTrigger);
Isas.components.register('progress', Progress);
Isas.components.register('radial-progress', RadialProgress);
Isas.components.register('steps', Steps);
Isas.components.register('stats', Stats);
Isas.components.register('tabs', Tabs);
Isas.components.register('tab-panels', TabPanels);
Isas.components.register('tab-content', TabContent);
Isas.components.register('timeline', Timeline);

export default isas;
export { install, autoInstall };
export { display } from './display/display.js';
export { parseComponentSpec, normalizeAttachmentSpec } from './plugin.js';
export { Isas } from './isas.js';
export { Component } from './component.js';
export { AdapterRegistry, ComponentRegistry } from './registries.js';
export { HostRuntime } from './host-runtime.js';
export { Alert } from './components/alert/alert.js';
export { Avatar } from './components/avatar/avatar.js';
export { Badge } from './components/badge/badge.js';
export { Button } from './components/button/button.js';
export { Card } from './components/card/card.js';
export { Chat } from './components/chat/chat.js';
export { Countdown } from './components/countdown/countdown.js';
export { Dialog } from './components/dialog/dialog.js';
export { DialogTrigger } from './components/dialog/dialog-trigger.js';
export { Divider } from './components/divider/divider.js';
export { Dock } from './components/dock/dock.js';
export { Dropdown } from './components/dropdown/dropdown.js';
export { DropdownTrigger } from './components/dropdown/dropdown-trigger.js';
export { Input } from './components/input/input.js';
export { InputField } from './components/input-field/input-field.js';
export { List } from './components/list/list.js';
export { Menu } from './components/menu/menu.js';
export { Option } from './components/option/option.js';
export { Otp } from './components/otp/otp.js';
export { Overlay } from './components/overlay/overlay.js';
export { OverlayTrigger } from './components/overlay/overlay-trigger.js';
export { Progress } from './components/progress/progress.js';
export { RadialProgress } from './components/radial-progress/radial-progress.js';
export { Select } from './components/select/select.js';
export { SelectControl } from './components/select/select-control.js';
export { SelectField } from './components/select-field/select-field.js';
export { Steps } from './components/steps/steps.js';
export { Stats } from './components/stats/stats.js';
export { TabContent } from './components/tabs/tab-content.js';
export { TabPanels } from './components/tabs/tab-panels.js';
export { Tabs } from './components/tabs/tabs.js';
export { Timeline } from './components/timeline/timeline.js';
export { Tooltip } from './components/tooltip/tooltip.js';
export { TargetComponent } from './components/surface/target-component.js';
export { TargetController } from './components/surface/target-controller.js';
export { targetRegistry } from './components/surface/target-registry.js';
export { AttributeBag, mergeClasses, mergeStyles } from './support/attribute-bag.js';
export { Slot } from './support/slot.js';
export { SLOT_CONTEXT_ATTRIBUTE, SlotBag } from './support/slot-bag.js';
export { Part } from './support/part.js';
export { PartBag } from './support/part-bag.js';
export {
    GENERATED_COMPONENT_ATTRIBUTE,
    generatedComponentAttributes,
    isGeneratedComponent,
} from './support/generated-component.js';
